//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSettingsStudio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppSettingsStudio.Resources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links cannot be established between Unix paths with Windows paths..
        /// </summary>
        internal static string CannotLink {
            get {
                return ResourceManager.GetString("CannotLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string DiffLeftLabel {
            get {
                return ResourceManager.GetString("DiffLeftLabel", resourceCulture);
            }
        }
        
        internal static string DiffRightLabel {
            get {
                return ResourceManager.GetString("DiffRightLabel", resourceCulture);
            }
        }
        
        internal static string DiffSideBySide {
            get {
                return ResourceManager.GetString("DiffSideBySide", resourceCulture);
            }
        }
        
        internal static string DiffIgnoreWhitespace {
            get {
                return ResourceManager.GetString("DiffIgnoreWhitespace", resourceCulture);
            }
        }
        
        internal static string DiffWordWrap {
            get {
                return ResourceManager.GetString("DiffWordWrap", resourceCulture);
            }
        }
        
        internal static string DiffShowWhitespace {
            get {
                return ResourceManager.GetString("DiffShowWhitespace", resourceCulture);
            }
        }
        
        internal static string DiffRefresh {
            get {
                return ResourceManager.GetString("DiffRefresh", resourceCulture);
            }
        }
        
        internal static string DiffChooseNode {
            get {
                return ResourceManager.GetString("DiffChooseNode", resourceCulture);
            }
        }
        
        internal static string DiffChooseLeft {
            get {
                return ResourceManager.GetString("DiffChooseLeft", resourceCulture);
            }
        }
        
        internal static string DiffChooseRight {
            get {
                return ResourceManager.GetString("DiffChooseRight", resourceCulture);
            }
        }
        
        internal static string DiffTitle {
            get {
                return ResourceManager.GetString("DiffTitle", resourceCulture);
            }
        }
        
        internal static string DiffTitleFormat {
            get {
                return ResourceManager.GetString("DiffTitleFormat", resourceCulture);
            }
        }
        
        internal static string DiffIdentical {
            get {
                return ResourceManager.GetString("DiffIdentical", resourceCulture);
            }
        }
        
        internal static string DiffStatsFormat {
            get {
                return ResourceManager.GetString("DiffStatsFormat", resourceCulture);
            }
        }
        
        internal static string DiffChooseTwoNodes {
            get {
                return ResourceManager.GetString("DiffChooseTwoNodes", resourceCulture);
            }
        }
        
        internal static string DiffComputing {
            get {
                return ResourceManager.GetString("DiffComputing", resourceCulture);
            }
        }
        
        internal static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        internal static string CompareTo {
            get {
                return ResourceManager.GetString("CompareTo", resourceCulture);
            }
        }
        
        internal static string ConfirmDiscardChanges {
            get {
                return ResourceManager.GetString("ConfirmDiscardChanges", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteInstance {
            get {
                return ResourceManager.GetString("ConfirmDeleteInstance", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteLinkedVirtualSettings {
            get {
                return ResourceManager.GetString("ConfirmDeleteLinkedVirtualSettings", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteVirtualSettings {
            get {
                return ResourceManager.GetString("ConfirmDeleteVirtualSettings", resourceCulture);
            }
        }
        
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        internal static string SaveFormat {
            get {
                return ResourceManager.GetString("SaveFormat", resourceCulture);
            }
        }
        
        internal static string PickAppSettingsTitle {
            get {
                return ResourceManager.GetString("PickAppSettingsTitle", resourceCulture);
            }
        }
        
        internal static string JsonFilesFilter {
            get {
                return ResourceManager.GetString("JsonFilesFilter", resourceCulture);
            }
        }
        
        internal static string ConfirmOverwriteFile {
            get {
                return ResourceManager.GetString("ConfirmOverwriteFile", resourceCulture);
            }
        }
        
        internal static string InvalidVirtualSettingsName {
            get {
                return ResourceManager.GetString("InvalidVirtualSettingsName", resourceCulture);
            }
        }
        
        internal static string DuplicateVirtualSettingsName {
            get {
                return ResourceManager.GetString("DuplicateVirtualSettingsName", resourceCulture);
            }
        }
        
        internal static string WebView2CheckError {
            get {
                return ResourceManager.GetString("WebView2CheckError", resourceCulture);
            }
        }
        
        internal static string ConfirmRemovePath {
            get {
                return ResourceManager.GetString("ConfirmRemovePath", resourceCulture);
            }
        }
        
        internal static string AddVariableTitle {
            get {
                return ResourceManager.GetString("AddVariableTitle", resourceCulture);
            }
        }
        
        internal static string ModifyVariableTitle {
            get {
                return ResourceManager.GetString("ModifyVariableTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteVariable {
            get {
                return ResourceManager.GetString("ConfirmDeleteVariable", resourceCulture);
            }
        }
    }
}
